### ISSUE TITLE
Is  9f411b3 still necessary 

### ISSUE THREAD

**Issue by MyGg29** [simonradier/node-red-contrib-selenium-wd2#11]
In 9f411b3 , patch 0.1.4, 
> Added a system of postinstall to patch selenium-webdriver http client behavior (temporary)

The patch http.js present in the project is now 6 months old. I don't really get why it exist but maybe selenium-webdriver got an actual patch ? 

https://github.com/simonradier/node-red-contrib-selenium-wd2/blob/7b8567d345afbf5498983c82544675b231ca9424/package.json#L39
This fix doesn't feel really good to use, especially since `cp` doesn't exist in windows, so you basicaly can't use the package in windows if you don't know what you're doing and don't use git bash

**Comment by simonradier** [comment]
Hi @MyGg29, 
This fix is needed because Selenium node.js version 4.0.X has a weird implementation of the webdriver management which prevent webdriver to be modified by node-red. The good news, is that I'm working on a 0.2.x which get rid of selenium webdriver implementation. No more dirty cp and it works on Windows / Linux / MacOS.
I'll publish a beta soon, so you will be able to test it.

I hope it answers your expectations. 

Best regards,

**Comment by MyGg29** [comment]
It does ! Thank you !
